---
processorlib: /home/boydb1/dax-processors
modulelib: /home/boydb1/dax-modules
singularity_imagedir: /scratch/boydb1/SINGULARITY_IMAGES
attrs:
  priority_project: TAYLOR_CAARE
  queue_limit: 100
  job_email: brian.d.boyd@vanderbilt.edu
  job_email_options: FAIL
  xnat_host: http://xnat2.vanderbilt.edu:8080/xnat
  skip_lastupdate: Y
modules:
  - name: d2n
    filepath: Module_dcm2niix.py
    arguments:
      dcm2niixpath: /scratch/boydb1/apps/dcm2niix_1jan2017/console/dcm2niix
  - name: limbo2xnat
    filepath: Module_edat_limbo2xnat.py
  - name: aa
    filepath: Module_Auto_Archive.py
    arguments: 
      email: brian.d.boyd@vanderbilt.edu
      api_key: API_KEY_CAARE
      arc_proj_filter: TAYLOR_CAARE
      pre_proj_filter: TAYLOR
      rc_subj_field: study_ident
      rc_subj_event: screen_arm_1
      rc_sess_field: mri_sesnid
      rc_sess_event: baseline_arm_1,phase1_8wk_arm_1
      rc_vuiis_field: mri_id
      rc_date_field: mri_date
      rc_proj_field: mri_xnat
yamlprocessors:
  - name: lst1
    filepath: LST_v1.1.0_processor.yaml
  - name: ma
    filepath: Multi_Atlas_v2.1.0_processor.yaml
  - name: fmriqa
    filepath: fMRIQA_v4.0.0_processor.yaml
  - name: fs6
    filepath: FS6_v1.2.0_processor.yaml
    arguments:
  - name: dtiqa
    filepath: dtiQA_v6.0.0_processor.yaml
  - name: edatqa_edp
    filepath: EDATQA_v1.0.6_processor.yaml
    arguments:
      inputs.defaults.resp_column: Probe_RESP,Probe1_RESP,Probe2_RESP,Probe3_RESP,Probe4_RESP
      inputs.defaults.type_column: Type
      inputs.defaults.rt_column: Probe_RT,Probe1_RT,Probe2_RT,Probe3_RT,Probe4_RT
      inputs.defaults.acc_column: Probe_ACC,Probe1_ACC,Probe2_ACC,Probe3_ACC,Probe4_ACC
      inputs.xnat.scans.scan1.types: fMRI_EDP
  - name: edatqa_nback
    filepath: EDATQA_v1.0.6_processor.yaml
    arguments:
      inputs.defaults.resp_column: StimText_RESP
      inputs.defaults.type_column: Nbackcondition
      inputs.defaults.rt_column: StimText_RT
      inputs.defaults.acc_column: StimText_ACC
      inputs.xnat.scans.scan1.types: fMRI_NBack,NBack_fMRI
  - name: rsfc
    filepath: RSFC_CONN_v1.0.1_processor.yaml
  - name: rwml
    filepath: RWML_v1.0.0_processor.yaml
  - name: tlobe
    filepath: Temporal_Lobe_v3.1.0_processor.yaml
  - name: tracula
    filepath: TRACULA_v2.0.0_processor.yaml
projects:
  - project: SCD_Mec
    yamlprocessors: fmriqa,fs6,lst1,ma,rsfc,tlobe
    modules: d2n
  - project: TAYLOR_CAARE
    modules: d2n,limbo2xnat,aa
    yamlprocessors: dtiqa,edatqa_edp,fmriqa,fs6,lst1,ma,rsfc,rwml,tracula
  - project: NIC
    yamlprocessors: dtiqa,edatqa_nback,fs6,lst1,ma,rsfc,rwml,tlobe,fmriqa
    modules: d2n,limbo2xnat
  - project: NIC_phantom
    modules: d2n
    yamlprocessors: rsfc,dtiqa,edatqa_nback,fmriqa,fs6,lst1,ma  
  - project: ACOBA 
    modules: d2n,limbo2xnat
    yamlprocessors: fmriqa,fs6,lst1,ma,rsfc,rwml

